name: Gen Stars List - JadeCong

run-name: Gen Stars List - JadeCong

on:
  schedule:
    - cron: "0 6 * * 1,3,5" # Run every monday, wednesday and friday at 6:00 AM
  workflow_dispatch: # Manual dispatch

permissions:
  contents: write

env:
  GH_TOKEN: ${{ github.token }}

defaults:
  run:
    shell: bash
    working-directory: ./scripts

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  gen-stars-list:
    name: Gen Stars List
    runs-on: [self-hosted, Linux, ARM64, JadeCong, runner-JadeCong]
    
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      
      - name: Configure git
        run: |
          git config --global user.name "github-actions[JadeCong-bot]"
          git config --global user.email "github-actions[JadeCong-bot]@users.noreply.github.com"
      
      - name: Run script gen-stars-list
        run: echo "JadeCong" | ./gen-stars-list.sh
        env:
          GH_TOKEN: ${{ github.token }}
      
      - name: Commit changes
        run: |
          cd ..
          git add .
          git commit -m "Update Stars List for JadeCong" || exit 0
      
      - name: Push changes
        run: git push
        env:
          GH_TOKEN: ${{ github.token }}
